# Generated by Django 4.2.4 on 2023-09-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLYE', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('cantidad', models.IntegerField()),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
