# Generated by Django 4.2.4 on 2023-09-04 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppLYE', '0003_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='nombre',
            new_name='producto',
        ),
    ]
