# Generated by Django 4.2.4 on 2023-09-04 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppLYE', '0004_rename_nombre_stock_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='sueldo',
            new_name='dni',
        ),
    ]
