# Generated by Django 4.2.4 on 2023-09-04 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppLYE', '0005_rename_sueldo_empleado_dni'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='dni',
            new_name='DNI',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='dni',
            new_name='DNI',
        ),
    ]
